# example profiles.yml file
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: student
      password: student
      port: 5432
      dbname: student
      schema: public
      threads: 4